name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    #  Bài 4: Định nghĩa ma trận hệ điều hành
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    # Chạy trên hệ điều hành tương ứng từ ma trận
    runs-on: ${{ matrix.os}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      # Bước dành cho Bài 1: Kiểm tra Dependency & Unit Test
      - name: Verify Bai 1
        working-directory: ./Bai1
        run: mvn clean test

      # Bước dành cho Bài 2: Kiểm tra Code Quality (Checkstyle)
      - name: Checkstyle Bai 2
        working-directory: ./Bai2
        run: mvn clean validate

      # Bước dành cho Bài 3: Build và Đóng gói (Yêu cầu chính bài 3)
      - name: Package Bai 3
        working-directory: ./Bai3
        run: mvn clean package

      # Bước dành cho Bài 3: Lưu trữ tệp .jar (Artifact)
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-package-bai3
          path: Bai3/target/*.jar
      # Bước cho Bài 5: Chạy Maven để JaCoCo sinh báo cáo
      - name: Build and Test Bai 5
        working-directory: ./Bai5
        run: mvn clean verify

      # Tải báo cáo lên GitHub Artifacts để giảng viên kiểm tra
      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report-bai5
          path: Bai5/target/site/jacoco/